CREATE DATABASE FLASH_FOOD;

USE FLASH_FOOD;

CREATE TABLE NHANVIEN(
    MaNV VARCHAR(200),
	email VARCHAR(200),
	password VARCHAR(100),
    HoTen NVARCHAR(200),
    NgaySinh VARCHAR(50),
    DiaChi NVARCHAR(1000),
    PRIMARY KEY (MaNV)
);

CREATE TABLE LOAISANPHAM(
    MaLoai VARCHAR(200),
    TenLoai NVARCHAR(500),
    GhiChu NVARCHAR(4000),
    PRIMARY KEY(MaLoai)
);

CREATE TABLE MONAN(
    MaMon VARCHAR(200),
    TenMon NVARCHAR(500),
    Gia INT ,
    Anh VARCHAR(500),
    MaLoai VARCHAR(200),
    PRIMARY KEY (MaMon),
    FOREIGN KEY (MaLoai)
        REFERENCES LOAISANPHAM (MaLoai)
        ON DELETE CASCADE
);

CREATE TABLE ORDERS(
    MaOrder VARCHAR (200),
    Ten NVARCHAR(500),
    GhiChu NVARCHAR(4000),
    PRIMARY KEY (MaOrder)
);

CREATE TABLE DONHANG(
    MaHoaDon VARCHAR(50),
    MaNV VARCHAR(200),
    TenKhach NVARCHAR(200),
    NgayDat DATE ,
    DiaChiGiao NVARCHAR(1000),
    SDT VARCHAR(12),
    GhiChu NVARCHAR(1000),
    PRIMARY KEY (MaHoaDon),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV)
);

CREATE TABLE CHITIETDON(
    ID INT,
    MaHoaDon VARCHAR (50) ,
    MaMon VARCHAR (200) ,
    SoLuong INT,
    DonGia INT,
    MaGiamGia VARCHAR (50),
    PRIMARY KEY (ID),
    FOREIGN KEY (MaHoaDon) REFERENCES DONHANG (MaHoaDon),
    FOREIGN KEY (MaMon) REFERENCES MONAN (MaMon)
);