use FLASH_FOOD;

insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('17-020 - Insurance', 'Carpenter', 81, 'https://robohash.org/nonsedest.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-140 - Vehicle Service Equipment', 'Stucco Mason', 56, 'https://robohash.org/fugasedest.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-518 - Temporary Water', 'Millwright', 25, 'https://robohash.org/inreprehenderitharum.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('3-300 - Footings', 'Plasterers', 73, 'https://robohash.org/veritatissintrepudiandae.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-520 - Construction Facilities', 'Millwright', 35, 'https://robohash.org/utomnissoluta.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('15-700 - Heating, Venting and Air Conditioning', 'Concrete Finisher', 78, 'https://robohash.org/harumremeum.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('5-200 - Metal Joists', 'Linemen', 74, 'https://robohash.org/quiquibusdamnecessitatibus.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('3-000 - General', 'Millwright', 99, 'https://robohash.org/sequiiureea.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('14-900 - Transportation', 'Refridgeration', 64, 'https://robohash.org/cumquemolestiasest.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('6-900 - Wood and Plastic Restoration and Cleaning', 'Cement Mason', 83, 'https://robohash.org/doloresoccaecatieius.png?size=50x50&set=set1','4-400 - Stone');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('16-800 - Sound and Video', 'Welder', 14, 'https://robohash.org/aliquidadipisciquidem.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('17-030 - Bond', 'Linemen', 55, 'https://robohash.org/eamagnisimilique.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('2-915 - Mulch', 'Welder', 53, 'https://robohash.org/consequatursedet.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('7-600 - Flashing and Sheet Metal', 'Brickmason', 31, 'https://robohash.org/quidelenitiaut.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('8-300 - Specialty Doors', 'Electrician', 94, 'https://robohash.org/dolorconsecteturcorrupti.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('4-900 - Masonry Restoration and Cleaning', 'Equipment Operator', 47, 'https://robohash.org/voluptatibusdoloremquesed.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('12-500 - Furniture', 'Tile Setter', 76, 'https://robohash.org/blanditiissitveritatis.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-640 - Owner Furnished Products', 'Pipefitter', 77, 'https://robohash.org/aliasutet.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('13-700 - Security Access and Surveillance', 'Plumber', 15, 'https://robohash.org/omnislaborumsimilique.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-400 - Food Service Equipment', 'Stucco Mason', 73, 'https://robohash.org/sitrepellendusest.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-460 - Unit Kitchens', 'Equipment Operator', 84, 'https://robohash.org/impeditnullaiusto.png?size=50x50&set=set1','13-900 - Fire Suppression');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('2-784 - Stone Unit Pavers', 'Safety Officer', 25, 'https://robohash.org/exercitationemabeum.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('8-050 - Basic Door and Window Materials and Methods', 'Cement Mason', 33, 'https://robohash.org/nesciuntquiassumenda.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('17-040 - Profit', 'Carpenter', 17, 'https://robohash.org/idrerumdoloribus.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-050 - Library Equipment', 'Terrazzo', 42, 'https://robohash.org/sedrerumut.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-570 - Temporary Controls', 'Plasterers', 35, 'https://robohash.org/accusamusdebitiset.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-642 - Owner Furnished Products', 'Ironworker', 56, 'https://robohash.org/dictamaximeullam.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('6 - Wood and Plastics', 'Plumber', 19, 'https://robohash.org/aliquamsuntvelit.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('2-782 - Brick Pavers', 'Linemen', 48, 'https://robohash.org/sitquisquamid.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-011 - Project Engineer', 'Equipment Operator', 33, 'https://robohash.org/beataereprehenderitquis.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('2-317 - Select Borrow', 'Landscaper', 55, 'https://robohash.org/saepesuntadipisci.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('14-700 - Turntables', 'Electrician', 55, 'https://robohash.org/consequaturporromollitia.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-010 - Maintenance Equipment', 'Glazier', 89, 'https://robohash.org/velittemporamolestias.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('3-320 - Slab Foundations', 'Pipelayer', 58, 'https://robohash.org/dolorealiquammolestias.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('10-400 - Identification Devices', 'Welder', 39, 'https://robohash.org/undequibusdamsit.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('8 - Doors and Windows', 'Brickmason', 80, 'https://robohash.org/quilaudantiumet.png?size=50x50&set=set1','4-700 - Simulated Masonry');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('10-240 - Grilles and Screens', 'Boilermaker', 94, 'https://robohash.org/temporibusnumquamdignissimos.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('6-500 - Structural Plastics', 'Millwright', 43, 'https://robohash.org/recusandaeminusvelit.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-130 - Audio-Visual Equipment', 'Plumber', 60, 'https://robohash.org/autiuredolore.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('2-924 - Sodding', 'Waterproofer', 95, 'https://robohash.org/voluptatevoluptatibusquod.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-514 - Temporary Heating, Cooling and Ventilation', 'Equipment Operator', 73, 'https://robohash.org/perferendisnamaccusamus.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('10-750 - Telephone Specialties', 'Boilermaker', 82, 'https://robohash.org/explicaboreiciendisest.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-517 - Temporary Telephone', 'Plumber', 81, 'https://robohash.org/blanditiisenimmaiores.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('13-110 - Cathodic Protection', 'Laborer', 76, 'https://robohash.org/debitissolutadignissimos.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-466 - Unit Kitchens', 'Brickmason', 61, 'https://robohash.org/velnatusperspiciatis.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('12-400 - Furnishings and Accessories', 'Ironworker', 91, 'https://robohash.org/delectusquiest.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-712 - Local Conditions', 'Pipefitter', 47, 'https://robohash.org/omnisaliquidet.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('15-050 - Basic Mechanical Materials and Methods', 'Cement Mason', 64, 'https://robohash.org/exercitationemblanditiisitaque.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('1-518 - Temporary Telephone', 'Concrete Finisher', 79, 'https://robohash.org/eaqueetcommodi.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
insert into MONAN (MaMon, TenMon, Gia, Anh, MaLoai) values ('11-450 - Residential Equipment', 'HVAC', 72, 'https://robohash.org/adipisciidlabore.png?size=50x50&set=set1','2-784 - Stone Unit Pavers');
